config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'sessions/new'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :posts, only: [:index, :new, :create, :show, :destroy] do
    resources :comments, only: [:create, :destroy]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :text, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :user_id, presence: true

  paginates_per 5
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  has_many :posts
  has_many :comments

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true,
    length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  before_save { email.downcase! }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_random_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_random_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(
      :remember_digest, nil
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  include SessionsHelper

  def record_not_found
    render plain: "404 Not Found", status: 404
  end

  def redirect_guest_user
    redirect_to login_path, flash: { error: "You must be logged in to access this section" }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :redirect_guest_user, unless: :logged_in?

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @post = @comment.post

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])

    if @comment.destroy
      redirect_to post_path(@comment.post)
    else
      redirect_to post_path(@comment.post), flash: { danger: "Error." }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text,:user_id,:post_id).merge({
      user_id: current_user.id
    })
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :redirect_guest_user, unless: :logged_in?
  skip_before_action :redirect_guest_user, only: [:index, :show]

  def index
    @posts = Post.page(params[:page])
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])

    if @post.destroy
      redirect_to posts_path
    else
      redirect_to post_path(@post), flash: { danger: "Error." }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :user_id).merge({
      user_id: current_user.id
    })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		remember user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
  	else
  		flash.now[:danger] = 'Invalid email/password combination' #Not quite right!
			render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  	
	#attr_accessible :user

  	def show
  		@user = User.find(params[:id])
  	end
	
  	def new
  		@user = User.new
  	end

	def create
	    @user = User.new(user_params)
	    #debugger
	    if @user.save
	    	log_in @user
	    	flash[:success] = "Welcome to the Sample App!"
	    	redirect_to @user
	      	# Handle a successful save.
			else
	      render 'new'
	    end
	end

	def destroy
	end

	private
  	
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
		base_title
	else
 		page_title + " | " + base_title
    end
end 
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
	end

	# Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
	end

	def log_out
		forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

	# Returns the current logged-in user (if any).
  def current_user
  	if (user_id = session[:user_id])
  		@current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
       user = User.find_by(id: user_id)
       if user && user.authenticated?(cookies[:remember_token])
					log_in user
         	@current_user = user
       end
		end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
	end

	def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar for the given user.
  	def gravatar_for(user)
    	gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    	gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    	image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/comments/index.html.erb
<h1>Comments#index,</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  	    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><a href="http://news.railstutorial.org/">News</a></li>
</ul> </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right"> 
        <li><%= link_to "Home", root_path %></li> 
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Post", posts_path %></li>
      
        <% if logged_in? %>
          <li><%= link_to "New Post", new_post_path %></li> 
          <li><%= link_to "Users", '#' %></li> 
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account 
              <b class="caret"></b>
            </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li> 
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
              </ul> 
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>

</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag 'application', media: 'all',
		'data-turbolinks-track' => true %> <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
  	</head>

  	<body>
    	<%= render 'layouts/header' %> 
    	<div class="container">
    		<% flash.each do |message_type, message| %>
    			<div class="alert alert-<%= message_type %>"><%= message %></div> 
    		<% end %>
			<%= yield %> 
		</div>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %> 
  	</body>
</html>

app/views/posts/index.html.erb
<% provide(:title, "index") %> 

<h1>Articles</h1>

<div class="clearfix">
  <% if @posts.empty? %>
    <p>There aint no post.</p>
  <% else %>
    <div class="posts">
      <% @posts.each do |post| %>
        <div class="post"> 
          <h3><%= link_to post.title, post_path(post.id) %></h3>
          <p><%= post.content %></p>
          <span class="bg-info"><%= pluralize(post.comments.count, "commentaire")%></span>
        </div>
      <% end %>
      <%= paginate @posts %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<% provide :title, 'New Post' %> 
<h1>New post</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

  <%= form_for @post do |f| %>
    <%= render partial: 'shared/error_messages', locals: { model: @post } %>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control', rows: '5' %>
      </div>

    <%= f.submit "Create the post", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, "show") %>

<h1>
  <%= @post.title %>
  <% if current_user == @post.user %>
    <small id="<%=dom_id(@post, :destroy)%>">
      <%= link_to " Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
    </small>
  <%end%>
</h1>

<div class="clearfix">
  <p><%= @post.content %></p>
  <hr/>

  <div class="comments">
    <div class="list-comments">
      <% if @post.comments.empty? %>
        <p>No comments.</p>
      <% else %>
        <% @post.comments.each do |comment| %>
          <div class="post">
            <b><%= comment.user.name %></b>
            <p>
              <i><%= comment.text %></i>
              <small id="<%=dom_id(comment, :destroy)%>">
                <% if current_user == comment.user %>
                  <%= link_to " Delete", post_comment_path(post_id: comment.post, id: comment.id), method: :delete, data: {confirm: "Are you sure?"} %>
                <% end %>
              </small>
            </p>
          </div>
        <% end %>
      <% end %>
    </div>
    
    <div class="form-comments">
      <% unless @comment.nil? %>
        <%= render partial: 'shared/error_messages', locals: { model: @comment } %>
      <% end %>
      <% if logged_in? %>
        <div class="row">
          <div class="col-md-5 col-md-offset-0"> 
            <%= form_for [@post, @post.comments.build] do |f| %>

              <div class="form-group">
                <%= f.text_field :text, class: 'form-control' %>
                <%= f.hidden_field :post_id, class: 'form-control' %>
              </div>
              <%= f.submit "Commenter", class: "btn btn-primary" %>
            <% end %>
          </div>  
        </div>  
      <% end %>
    </div>

  </div>

</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %> 
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(model.errors.count, "error") %>.
    </div>
    
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li> 
      <% end %>
    </ul>
  </div> 
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %> <h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %> <h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %> 
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
<h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
</h2>
<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %> 
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %> 
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_for(@user) do |f| %> 
	<%= render partial: 'shared/error_messages', locals: { model: @user } %>

	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label :email %>
	<%= f.email_field :email, class: 'form-control' %>

	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>

	<%= f.label :password_confirmation, "Confirmation" %> 
	<%= f.password_field :password_confirmation, class: 'form-control' %>

	<%= f.submit "Create my account", class: "btn btn-primary" %>
	<% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %> 
<div class="row">
	<aside class="col-md-4">
    <section class="user_info">
	<h1>
		<%= gravatar_for @user %>
		<%= @user.name %> 
	</h1>
    </section>
  	</aside>
</div>